[package]
name = "projecteuler_rs"
version = "0.1.0"
authors = ["Yakup TURKAN"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
pe_0001 = []
pe_0002 = []